package cn.edu.suda.schoolBus.dao;

import cn.edu.suda.schoolBus.bean.CarNumber;
import cn.edu.suda.schoolBus.bean.CarNumberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int countByExample(CarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByExample(CarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByPrimaryKey(Integer cnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insert(CarNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insertSelective(CarNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    List<CarNumber> selectByExample(CarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    CarNumber selectByPrimaryKey(Integer cnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") CarNumber record, @Param("example") CarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExample(@Param("record") CarNumber record, @Param("example") CarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKeySelective(CarNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKey(CarNumber record);
}