package cn.edu.suda.schoolBus.dao;

import cn.edu.suda.schoolBus.bean.DepartureInfo;
import cn.edu.suda.schoolBus.bean.DepartureInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartureInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int countByExample(DepartureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByExample(DepartureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByPrimaryKey(Integer diId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insert(DepartureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insertSelective(DepartureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    List<DepartureInfo> selectByExample(DepartureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    DepartureInfo selectByPrimaryKey(Integer diId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") DepartureInfo record, @Param("example") DepartureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExample(@Param("record") DepartureInfo record, @Param("example") DepartureInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKeySelective(DepartureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKey(DepartureInfo record);
}