package cn.edu.suda.schoolBus.dao;

import cn.edu.suda.schoolBus.bean.Driver;
import cn.edu.suda.schoolBus.bean.DriverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int countByExample(DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByExample(DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insertSelective(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    List<Driver> selectByExample(DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    Driver selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") Driver record, @Param("example") DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExample(@Param("record") Driver record, @Param("example") DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKeySelective(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKey(Driver record);
}