package cn.edu.suda.schoolBus.dao;

import cn.edu.suda.schoolBus.bean.DynamicCarNumber;
import cn.edu.suda.schoolBus.bean.DynamicCarNumberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DynamicCarNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int countByExample(DynamicCarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByExample(DynamicCarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByPrimaryKey(Integer dcnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insert(DynamicCarNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insertSelective(DynamicCarNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    List<DynamicCarNumber> selectByExample(DynamicCarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    DynamicCarNumber selectByPrimaryKey(Integer dcnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") DynamicCarNumber record, @Param("example") DynamicCarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExample(@Param("record") DynamicCarNumber record, @Param("example") DynamicCarNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKeySelective(DynamicCarNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKey(DynamicCarNumber record);
}