package cn.edu.suda.schoolBus.dao;

import cn.edu.suda.schoolBus.bean.SchoolBus;
import cn.edu.suda.schoolBus.bean.SchoolBusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolBusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int countByExample(SchoolBusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByExample(SchoolBusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int deleteByPrimaryKey(Integer sbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insert(SchoolBus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int insertSelective(SchoolBus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    List<SchoolBus> selectByExample(SchoolBusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    SchoolBus selectByPrimaryKey(Integer sbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") SchoolBus record, @Param("example") SchoolBusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByExample(@Param("record") SchoolBus record, @Param("example") SchoolBusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKeySelective(SchoolBus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    int updateByPrimaryKey(SchoolBus record);
}