package cn.edu.suda.schoolBus.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public AdminUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAuIdIsNull() {
            addCriterion("au_id is null");
            return (Criteria) this;
        }

        public Criteria andAuIdIsNotNull() {
            addCriterion("au_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuIdEqualTo(Integer value) {
            addCriterion("au_id =", value, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdNotEqualTo(Integer value) {
            addCriterion("au_id <>", value, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdGreaterThan(Integer value) {
            addCriterion("au_id >", value, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("au_id >=", value, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdLessThan(Integer value) {
            addCriterion("au_id <", value, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdLessThanOrEqualTo(Integer value) {
            addCriterion("au_id <=", value, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdIn(List<Integer> values) {
            addCriterion("au_id in", values, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdNotIn(List<Integer> values) {
            addCriterion("au_id not in", values, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdBetween(Integer value1, Integer value2) {
            addCriterion("au_id between", value1, value2, "auId");
            return (Criteria) this;
        }

        public Criteria andAuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("au_id not between", value1, value2, "auId");
            return (Criteria) this;
        }

        public Criteria andAuAccountIsNull() {
            addCriterion("au_account is null");
            return (Criteria) this;
        }

        public Criteria andAuAccountIsNotNull() {
            addCriterion("au_account is not null");
            return (Criteria) this;
        }

        public Criteria andAuAccountEqualTo(String value) {
            addCriterion("au_account =", value, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountNotEqualTo(String value) {
            addCriterion("au_account <>", value, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountGreaterThan(String value) {
            addCriterion("au_account >", value, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountGreaterThanOrEqualTo(String value) {
            addCriterion("au_account >=", value, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountLessThan(String value) {
            addCriterion("au_account <", value, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountLessThanOrEqualTo(String value) {
            addCriterion("au_account <=", value, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountLike(String value) {
            addCriterion("au_account like", value, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountNotLike(String value) {
            addCriterion("au_account not like", value, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountIn(List<String> values) {
            addCriterion("au_account in", values, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountNotIn(List<String> values) {
            addCriterion("au_account not in", values, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountBetween(String value1, String value2) {
            addCriterion("au_account between", value1, value2, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuAccountNotBetween(String value1, String value2) {
            addCriterion("au_account not between", value1, value2, "auAccount");
            return (Criteria) this;
        }

        public Criteria andAuPasswdIsNull() {
            addCriterion("au_passwd is null");
            return (Criteria) this;
        }

        public Criteria andAuPasswdIsNotNull() {
            addCriterion("au_passwd is not null");
            return (Criteria) this;
        }

        public Criteria andAuPasswdEqualTo(String value) {
            addCriterion("au_passwd =", value, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdNotEqualTo(String value) {
            addCriterion("au_passwd <>", value, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdGreaterThan(String value) {
            addCriterion("au_passwd >", value, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("au_passwd >=", value, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdLessThan(String value) {
            addCriterion("au_passwd <", value, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdLessThanOrEqualTo(String value) {
            addCriterion("au_passwd <=", value, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdLike(String value) {
            addCriterion("au_passwd like", value, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdNotLike(String value) {
            addCriterion("au_passwd not like", value, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdIn(List<String> values) {
            addCriterion("au_passwd in", values, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdNotIn(List<String> values) {
            addCriterion("au_passwd not in", values, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdBetween(String value1, String value2) {
            addCriterion("au_passwd between", value1, value2, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuPasswdNotBetween(String value1, String value2) {
            addCriterion("au_passwd not between", value1, value2, "auPasswd");
            return (Criteria) this;
        }

        public Criteria andAuTimeIsNull() {
            addCriterion("au_time is null");
            return (Criteria) this;
        }

        public Criteria andAuTimeIsNotNull() {
            addCriterion("au_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuTimeEqualTo(Date value) {
            addCriterion("au_time =", value, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeNotEqualTo(Date value) {
            addCriterion("au_time <>", value, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeGreaterThan(Date value) {
            addCriterion("au_time >", value, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("au_time >=", value, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeLessThan(Date value) {
            addCriterion("au_time <", value, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeLessThanOrEqualTo(Date value) {
            addCriterion("au_time <=", value, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeIn(List<Date> values) {
            addCriterion("au_time in", values, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeNotIn(List<Date> values) {
            addCriterion("au_time not in", values, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeBetween(Date value1, Date value2) {
            addCriterion("au_time between", value1, value2, "auTime");
            return (Criteria) this;
        }

        public Criteria andAuTimeNotBetween(Date value1, Date value2) {
            addCriterion("au_time not between", value1, value2, "auTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_user
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 10 16:10:16 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin_user
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}