package cn.edu.suda.schoolBus.bean;

import java.util.Date;

public class Appointment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.a_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.a_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Date aTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.relate_to_passenger
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer relateToPassenger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.relate_to_dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer relateToDynamicCarNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.a_id
     *
     * @return the value of appointment.a_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.a_id
     *
     * @param aId the value for appointment.a_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.a_time
     *
     * @return the value of appointment.a_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Date getaTime() {
        return aTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.a_time
     *
     * @param aTime the value for appointment.a_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setaTime(Date aTime) {
        this.aTime = aTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.relate_to_passenger
     *
     * @return the value of appointment.relate_to_passenger
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getRelateToPassenger() {
        return relateToPassenger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.relate_to_passenger
     *
     * @param relateToPassenger the value for appointment.relate_to_passenger
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setRelateToPassenger(Integer relateToPassenger) {
        this.relateToPassenger = relateToPassenger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.relate_to_dynamic_car_number
     *
     * @return the value of appointment.relate_to_dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getRelateToDynamicCarNumber() {
        return relateToDynamicCarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.relate_to_dynamic_car_number
     *
     * @param relateToDynamicCarNumber the value for appointment.relate_to_dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setRelateToDynamicCarNumber(Integer relateToDynamicCarNumber) {
        this.relateToDynamicCarNumber = relateToDynamicCarNumber;
    }
}