package cn.edu.suda.schoolBus.bean;

import java.util.Date;

public class CarNumber {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_number.cn_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer cnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_number.departure_place
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private String departurePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_number.departure_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Date departureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_number.cn_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer cnStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_number.cn_id
     *
     * @return the value of car_number.cn_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getCnId() {
        return cnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_number.cn_id
     *
     * @param cnId the value for car_number.cn_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setCnId(Integer cnId) {
        this.cnId = cnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_number.departure_place
     *
     * @return the value of car_number.departure_place
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getDeparturePlace() {
        return departurePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_number.departure_place
     *
     * @param departurePlace the value for car_number.departure_place
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDeparturePlace(String departurePlace) {
        this.departurePlace = departurePlace == null ? null : departurePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_number.departure_time
     *
     * @return the value of car_number.departure_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Date getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_number.departure_time
     *
     * @param departureTime the value for car_number.departure_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_number.cn_status
     *
     * @return the value of car_number.cn_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getCnStatus() {
        return cnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_number.cn_status
     *
     * @param cnStatus the value for car_number.cn_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setCnStatus(Integer cnStatus) {
        this.cnStatus = cnStatus;
    }
}