package cn.edu.suda.schoolBus.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DepartureInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public DepartureInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDiIdIsNull() {
            addCriterion("di_id is null");
            return (Criteria) this;
        }

        public Criteria andDiIdIsNotNull() {
            addCriterion("di_id is not null");
            return (Criteria) this;
        }

        public Criteria andDiIdEqualTo(Integer value) {
            addCriterion("di_id =", value, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdNotEqualTo(Integer value) {
            addCriterion("di_id <>", value, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdGreaterThan(Integer value) {
            addCriterion("di_id >", value, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("di_id >=", value, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdLessThan(Integer value) {
            addCriterion("di_id <", value, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdLessThanOrEqualTo(Integer value) {
            addCriterion("di_id <=", value, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdIn(List<Integer> values) {
            addCriterion("di_id in", values, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdNotIn(List<Integer> values) {
            addCriterion("di_id not in", values, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdBetween(Integer value1, Integer value2) {
            addCriterion("di_id between", value1, value2, "diId");
            return (Criteria) this;
        }

        public Criteria andDiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("di_id not between", value1, value2, "diId");
            return (Criteria) this;
        }

        public Criteria andDiTimeIsNull() {
            addCriterion("di_time is null");
            return (Criteria) this;
        }

        public Criteria andDiTimeIsNotNull() {
            addCriterion("di_time is not null");
            return (Criteria) this;
        }

        public Criteria andDiTimeEqualTo(Date value) {
            addCriterion("di_time =", value, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeNotEqualTo(Date value) {
            addCriterion("di_time <>", value, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeGreaterThan(Date value) {
            addCriterion("di_time >", value, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("di_time >=", value, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeLessThan(Date value) {
            addCriterion("di_time <", value, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeLessThanOrEqualTo(Date value) {
            addCriterion("di_time <=", value, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeIn(List<Date> values) {
            addCriterion("di_time in", values, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeNotIn(List<Date> values) {
            addCriterion("di_time not in", values, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeBetween(Date value1, Date value2) {
            addCriterion("di_time between", value1, value2, "diTime");
            return (Criteria) this;
        }

        public Criteria andDiTimeNotBetween(Date value1, Date value2) {
            addCriterion("di_time not between", value1, value2, "diTime");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberIsNull() {
            addCriterion("relate_to_dynamic_car_number is null");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberIsNotNull() {
            addCriterion("relate_to_dynamic_car_number is not null");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberEqualTo(Integer value) {
            addCriterion("relate_to_dynamic_car_number =", value, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberNotEqualTo(Integer value) {
            addCriterion("relate_to_dynamic_car_number <>", value, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberGreaterThan(Integer value) {
            addCriterion("relate_to_dynamic_car_number >", value, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("relate_to_dynamic_car_number >=", value, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberLessThan(Integer value) {
            addCriterion("relate_to_dynamic_car_number <", value, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberLessThanOrEqualTo(Integer value) {
            addCriterion("relate_to_dynamic_car_number <=", value, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberIn(List<Integer> values) {
            addCriterion("relate_to_dynamic_car_number in", values, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberNotIn(List<Integer> values) {
            addCriterion("relate_to_dynamic_car_number not in", values, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberBetween(Integer value1, Integer value2) {
            addCriterion("relate_to_dynamic_car_number between", value1, value2, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDynamicCarNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("relate_to_dynamic_car_number not between", value1, value2, "relateToDynamicCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverIsNull() {
            addCriterion("relate_to_driver is null");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverIsNotNull() {
            addCriterion("relate_to_driver is not null");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverEqualTo(Integer value) {
            addCriterion("relate_to_driver =", value, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverNotEqualTo(Integer value) {
            addCriterion("relate_to_driver <>", value, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverGreaterThan(Integer value) {
            addCriterion("relate_to_driver >", value, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverGreaterThanOrEqualTo(Integer value) {
            addCriterion("relate_to_driver >=", value, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverLessThan(Integer value) {
            addCriterion("relate_to_driver <", value, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverLessThanOrEqualTo(Integer value) {
            addCriterion("relate_to_driver <=", value, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverIn(List<Integer> values) {
            addCriterion("relate_to_driver in", values, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverNotIn(List<Integer> values) {
            addCriterion("relate_to_driver not in", values, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverBetween(Integer value1, Integer value2) {
            addCriterion("relate_to_driver between", value1, value2, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToDriverNotBetween(Integer value1, Integer value2) {
            addCriterion("relate_to_driver not between", value1, value2, "relateToDriver");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusIsNull() {
            addCriterion("relate_to_school_bus is null");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusIsNotNull() {
            addCriterion("relate_to_school_bus is not null");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusEqualTo(Integer value) {
            addCriterion("relate_to_school_bus =", value, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusNotEqualTo(Integer value) {
            addCriterion("relate_to_school_bus <>", value, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusGreaterThan(Integer value) {
            addCriterion("relate_to_school_bus >", value, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusGreaterThanOrEqualTo(Integer value) {
            addCriterion("relate_to_school_bus >=", value, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusLessThan(Integer value) {
            addCriterion("relate_to_school_bus <", value, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusLessThanOrEqualTo(Integer value) {
            addCriterion("relate_to_school_bus <=", value, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusIn(List<Integer> values) {
            addCriterion("relate_to_school_bus in", values, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusNotIn(List<Integer> values) {
            addCriterion("relate_to_school_bus not in", values, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusBetween(Integer value1, Integer value2) {
            addCriterion("relate_to_school_bus between", value1, value2, "relateToSchoolBus");
            return (Criteria) this;
        }

        public Criteria andRelateToSchoolBusNotBetween(Integer value1, Integer value2) {
            addCriterion("relate_to_school_bus not between", value1, value2, "relateToSchoolBus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table departure_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 10 16:10:16 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table departure_info
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}