package cn.edu.suda.schoolBus.bean;

import java.util.Date;

public class DepartureInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departure_info.di_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer diId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departure_info.di_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Date diTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departure_info.relate_to_dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer relateToDynamicCarNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departure_info.relate_to_driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer relateToDriver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departure_info.relate_to_school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer relateToSchoolBus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departure_info.di_id
     *
     * @return the value of departure_info.di_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getDiId() {
        return diId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departure_info.di_id
     *
     * @param diId the value for departure_info.di_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDiId(Integer diId) {
        this.diId = diId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departure_info.di_time
     *
     * @return the value of departure_info.di_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Date getDiTime() {
        return diTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departure_info.di_time
     *
     * @param diTime the value for departure_info.di_time
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDiTime(Date diTime) {
        this.diTime = diTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departure_info.relate_to_dynamic_car_number
     *
     * @return the value of departure_info.relate_to_dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getRelateToDynamicCarNumber() {
        return relateToDynamicCarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departure_info.relate_to_dynamic_car_number
     *
     * @param relateToDynamicCarNumber the value for departure_info.relate_to_dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setRelateToDynamicCarNumber(Integer relateToDynamicCarNumber) {
        this.relateToDynamicCarNumber = relateToDynamicCarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departure_info.relate_to_driver
     *
     * @return the value of departure_info.relate_to_driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getRelateToDriver() {
        return relateToDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departure_info.relate_to_driver
     *
     * @param relateToDriver the value for departure_info.relate_to_driver
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setRelateToDriver(Integer relateToDriver) {
        this.relateToDriver = relateToDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departure_info.relate_to_school_bus
     *
     * @return the value of departure_info.relate_to_school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getRelateToSchoolBus() {
        return relateToSchoolBus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departure_info.relate_to_school_bus
     *
     * @param relateToSchoolBus the value for departure_info.relate_to_school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setRelateToSchoolBus(Integer relateToSchoolBus) {
        this.relateToSchoolBus = relateToSchoolBus;
    }
}