package cn.edu.suda.schoolBus.bean;

public class Driver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.d_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.d_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private String dNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.d_name
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.d_phone
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private String dPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.d_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer dStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.d_id
     *
     * @return the value of driver.d_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.d_id
     *
     * @param dId the value for driver.d_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.d_number
     *
     * @return the value of driver.d_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getdNumber() {
        return dNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.d_number
     *
     * @param dNumber the value for driver.d_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setdNumber(String dNumber) {
        this.dNumber = dNumber == null ? null : dNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.d_name
     *
     * @return the value of driver.d_name
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.d_name
     *
     * @param dName the value for driver.d_name
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.d_phone
     *
     * @return the value of driver.d_phone
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getdPhone() {
        return dPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.d_phone
     *
     * @param dPhone the value for driver.d_phone
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setdPhone(String dPhone) {
        this.dPhone = dPhone == null ? null : dPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.d_status
     *
     * @return the value of driver.d_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getdStatus() {
        return dStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.d_status
     *
     * @param dStatus the value for driver.d_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setdStatus(Integer dStatus) {
        this.dStatus = dStatus;
    }
}