package cn.edu.suda.schoolBus.bean;

public class DynamicCarNumber {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_car_number.dcn_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer dcnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_car_number.current_passenger_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer currentPassengerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_car_number.dcn_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer dcnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamic_car_number.relate_to_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer relateToCarNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_car_number.dcn_id
     *
     * @return the value of dynamic_car_number.dcn_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getDcnId() {
        return dcnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_car_number.dcn_id
     *
     * @param dcnId the value for dynamic_car_number.dcn_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDcnId(Integer dcnId) {
        this.dcnId = dcnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_car_number.current_passenger_number
     *
     * @return the value of dynamic_car_number.current_passenger_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getCurrentPassengerNumber() {
        return currentPassengerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_car_number.current_passenger_number
     *
     * @param currentPassengerNumber the value for dynamic_car_number.current_passenger_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setCurrentPassengerNumber(Integer currentPassengerNumber) {
        this.currentPassengerNumber = currentPassengerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_car_number.dcn_status
     *
     * @return the value of dynamic_car_number.dcn_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getDcnStatus() {
        return dcnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_car_number.dcn_status
     *
     * @param dcnStatus the value for dynamic_car_number.dcn_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDcnStatus(Integer dcnStatus) {
        this.dcnStatus = dcnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamic_car_number.relate_to_car_number
     *
     * @return the value of dynamic_car_number.relate_to_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getRelateToCarNumber() {
        return relateToCarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamic_car_number.relate_to_car_number
     *
     * @param relateToCarNumber the value for dynamic_car_number.relate_to_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setRelateToCarNumber(Integer relateToCarNumber) {
        this.relateToCarNumber = relateToCarNumber;
    }
}