package cn.edu.suda.schoolBus.bean;

import java.util.ArrayList;
import java.util.List;

public class DynamicCarNumberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public DynamicCarNumberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDcnIdIsNull() {
            addCriterion("dcn_id is null");
            return (Criteria) this;
        }

        public Criteria andDcnIdIsNotNull() {
            addCriterion("dcn_id is not null");
            return (Criteria) this;
        }

        public Criteria andDcnIdEqualTo(Integer value) {
            addCriterion("dcn_id =", value, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdNotEqualTo(Integer value) {
            addCriterion("dcn_id <>", value, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdGreaterThan(Integer value) {
            addCriterion("dcn_id >", value, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dcn_id >=", value, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdLessThan(Integer value) {
            addCriterion("dcn_id <", value, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdLessThanOrEqualTo(Integer value) {
            addCriterion("dcn_id <=", value, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdIn(List<Integer> values) {
            addCriterion("dcn_id in", values, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdNotIn(List<Integer> values) {
            addCriterion("dcn_id not in", values, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdBetween(Integer value1, Integer value2) {
            addCriterion("dcn_id between", value1, value2, "dcnId");
            return (Criteria) this;
        }

        public Criteria andDcnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dcn_id not between", value1, value2, "dcnId");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberIsNull() {
            addCriterion("current_passenger_number is null");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberIsNotNull() {
            addCriterion("current_passenger_number is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberEqualTo(Integer value) {
            addCriterion("current_passenger_number =", value, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberNotEqualTo(Integer value) {
            addCriterion("current_passenger_number <>", value, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberGreaterThan(Integer value) {
            addCriterion("current_passenger_number >", value, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("current_passenger_number >=", value, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberLessThan(Integer value) {
            addCriterion("current_passenger_number <", value, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberLessThanOrEqualTo(Integer value) {
            addCriterion("current_passenger_number <=", value, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberIn(List<Integer> values) {
            addCriterion("current_passenger_number in", values, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberNotIn(List<Integer> values) {
            addCriterion("current_passenger_number not in", values, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberBetween(Integer value1, Integer value2) {
            addCriterion("current_passenger_number between", value1, value2, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andCurrentPassengerNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("current_passenger_number not between", value1, value2, "currentPassengerNumber");
            return (Criteria) this;
        }

        public Criteria andDcnStatusIsNull() {
            addCriterion("dcn_status is null");
            return (Criteria) this;
        }

        public Criteria andDcnStatusIsNotNull() {
            addCriterion("dcn_status is not null");
            return (Criteria) this;
        }

        public Criteria andDcnStatusEqualTo(Integer value) {
            addCriterion("dcn_status =", value, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusNotEqualTo(Integer value) {
            addCriterion("dcn_status <>", value, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusGreaterThan(Integer value) {
            addCriterion("dcn_status >", value, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("dcn_status >=", value, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusLessThan(Integer value) {
            addCriterion("dcn_status <", value, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusLessThanOrEqualTo(Integer value) {
            addCriterion("dcn_status <=", value, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusIn(List<Integer> values) {
            addCriterion("dcn_status in", values, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusNotIn(List<Integer> values) {
            addCriterion("dcn_status not in", values, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusBetween(Integer value1, Integer value2) {
            addCriterion("dcn_status between", value1, value2, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andDcnStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("dcn_status not between", value1, value2, "dcnStatus");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberIsNull() {
            addCriterion("relate_to_car_number is null");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberIsNotNull() {
            addCriterion("relate_to_car_number is not null");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberEqualTo(Integer value) {
            addCriterion("relate_to_car_number =", value, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberNotEqualTo(Integer value) {
            addCriterion("relate_to_car_number <>", value, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberGreaterThan(Integer value) {
            addCriterion("relate_to_car_number >", value, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("relate_to_car_number >=", value, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberLessThan(Integer value) {
            addCriterion("relate_to_car_number <", value, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberLessThanOrEqualTo(Integer value) {
            addCriterion("relate_to_car_number <=", value, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberIn(List<Integer> values) {
            addCriterion("relate_to_car_number in", values, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberNotIn(List<Integer> values) {
            addCriterion("relate_to_car_number not in", values, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberBetween(Integer value1, Integer value2) {
            addCriterion("relate_to_car_number between", value1, value2, "relateToCarNumber");
            return (Criteria) this;
        }

        public Criteria andRelateToCarNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("relate_to_car_number not between", value1, value2, "relateToCarNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dynamic_car_number
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 10 16:10:16 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dynamic_car_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}