package cn.edu.suda.schoolBus.bean;

public class Passenger {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.p_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.p_account
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private String pAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.p_passwd
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private String pPasswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.p_sort
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer pSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.p_id
     *
     * @return the value of passenger.p_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.p_id
     *
     * @param pId the value for passenger.p_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.p_account
     *
     * @return the value of passenger.p_account
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getpAccount() {
        return pAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.p_account
     *
     * @param pAccount the value for passenger.p_account
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setpAccount(String pAccount) {
        this.pAccount = pAccount == null ? null : pAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.p_passwd
     *
     * @return the value of passenger.p_passwd
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getpPasswd() {
        return pPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.p_passwd
     *
     * @param pPasswd the value for passenger.p_passwd
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setpPasswd(String pPasswd) {
        this.pPasswd = pPasswd == null ? null : pPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.p_sort
     *
     * @return the value of passenger.p_sort
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getpSort() {
        return pSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.p_sort
     *
     * @param pSort the value for passenger.p_sort
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setpSort(Integer pSort) {
        this.pSort = pSort;
    }
}