package cn.edu.suda.schoolBus.bean;

import java.util.ArrayList;
import java.util.List;

public class SchoolBusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public SchoolBusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSbIdIsNull() {
            addCriterion("sb_id is null");
            return (Criteria) this;
        }

        public Criteria andSbIdIsNotNull() {
            addCriterion("sb_id is not null");
            return (Criteria) this;
        }

        public Criteria andSbIdEqualTo(Integer value) {
            addCriterion("sb_id =", value, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdNotEqualTo(Integer value) {
            addCriterion("sb_id <>", value, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdGreaterThan(Integer value) {
            addCriterion("sb_id >", value, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sb_id >=", value, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdLessThan(Integer value) {
            addCriterion("sb_id <", value, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdLessThanOrEqualTo(Integer value) {
            addCriterion("sb_id <=", value, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdIn(List<Integer> values) {
            addCriterion("sb_id in", values, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdNotIn(List<Integer> values) {
            addCriterion("sb_id not in", values, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdBetween(Integer value1, Integer value2) {
            addCriterion("sb_id between", value1, value2, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sb_id not between", value1, value2, "sbId");
            return (Criteria) this;
        }

        public Criteria andSbNumberIsNull() {
            addCriterion("sb_number is null");
            return (Criteria) this;
        }

        public Criteria andSbNumberIsNotNull() {
            addCriterion("sb_number is not null");
            return (Criteria) this;
        }

        public Criteria andSbNumberEqualTo(String value) {
            addCriterion("sb_number =", value, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberNotEqualTo(String value) {
            addCriterion("sb_number <>", value, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberGreaterThan(String value) {
            addCriterion("sb_number >", value, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberGreaterThanOrEqualTo(String value) {
            addCriterion("sb_number >=", value, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberLessThan(String value) {
            addCriterion("sb_number <", value, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberLessThanOrEqualTo(String value) {
            addCriterion("sb_number <=", value, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberLike(String value) {
            addCriterion("sb_number like", value, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberNotLike(String value) {
            addCriterion("sb_number not like", value, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberIn(List<String> values) {
            addCriterion("sb_number in", values, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberNotIn(List<String> values) {
            addCriterion("sb_number not in", values, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberBetween(String value1, String value2) {
            addCriterion("sb_number between", value1, value2, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbNumberNotBetween(String value1, String value2) {
            addCriterion("sb_number not between", value1, value2, "sbNumber");
            return (Criteria) this;
        }

        public Criteria andSbStatusIsNull() {
            addCriterion("sb_status is null");
            return (Criteria) this;
        }

        public Criteria andSbStatusIsNotNull() {
            addCriterion("sb_status is not null");
            return (Criteria) this;
        }

        public Criteria andSbStatusEqualTo(Integer value) {
            addCriterion("sb_status =", value, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusNotEqualTo(Integer value) {
            addCriterion("sb_status <>", value, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusGreaterThan(Integer value) {
            addCriterion("sb_status >", value, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sb_status >=", value, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusLessThan(Integer value) {
            addCriterion("sb_status <", value, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sb_status <=", value, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusIn(List<Integer> values) {
            addCriterion("sb_status in", values, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusNotIn(List<Integer> values) {
            addCriterion("sb_status not in", values, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusBetween(Integer value1, Integer value2) {
            addCriterion("sb_status between", value1, value2, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andSbStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sb_status not between", value1, value2, "sbStatus");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberIsNull() {
            addCriterion("passenger_number is null");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberIsNotNull() {
            addCriterion("passenger_number is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberEqualTo(Integer value) {
            addCriterion("passenger_number =", value, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberNotEqualTo(Integer value) {
            addCriterion("passenger_number <>", value, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberGreaterThan(Integer value) {
            addCriterion("passenger_number >", value, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("passenger_number >=", value, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberLessThan(Integer value) {
            addCriterion("passenger_number <", value, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberLessThanOrEqualTo(Integer value) {
            addCriterion("passenger_number <=", value, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberIn(List<Integer> values) {
            addCriterion("passenger_number in", values, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberNotIn(List<Integer> values) {
            addCriterion("passenger_number not in", values, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberBetween(Integer value1, Integer value2) {
            addCriterion("passenger_number between", value1, value2, "passengerNumber");
            return (Criteria) this;
        }

        public Criteria andPassengerNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("passenger_number not between", value1, value2, "passengerNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_bus
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 10 16:10:16 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school_bus
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}