package cn.edu.suda.schoolBus.bean;

public class SchoolBus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus.sb_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer sbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus.sb_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private String sbNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus.sb_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer sbStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_bus.passenger_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    private Integer passengerNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus.sb_id
     *
     * @return the value of school_bus.sb_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getSbId() {
        return sbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus.sb_id
     *
     * @param sbId the value for school_bus.sb_id
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setSbId(Integer sbId) {
        this.sbId = sbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus.sb_number
     *
     * @return the value of school_bus.sb_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public String getSbNumber() {
        return sbNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus.sb_number
     *
     * @param sbNumber the value for school_bus.sb_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setSbNumber(String sbNumber) {
        this.sbNumber = sbNumber == null ? null : sbNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus.sb_status
     *
     * @return the value of school_bus.sb_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getSbStatus() {
        return sbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus.sb_status
     *
     * @param sbStatus the value for school_bus.sb_status
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setSbStatus(Integer sbStatus) {
        this.sbStatus = sbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_bus.passenger_number
     *
     * @return the value of school_bus.passenger_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public Integer getPassengerNumber() {
        return passengerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_bus.passenger_number
     *
     * @param passengerNumber the value for school_bus.passenger_number
     *
     * @mbggenerated Sun Apr 10 16:10:16 CST 2016
     */
    public void setPassengerNumber(Integer passengerNumber) {
        this.passengerNumber = passengerNumber;
    }
}